FROM golang:1.7.4-onbuild
# FROM golang:1.7.4

# RUN mkdir -p /go/src/app
# WORKDIR /go/src/app

# # this will ideally be built by the ONBUILD below ;)
# CMD ["go-wrapper", "run"]

# COPY . /go/src/app
# RUN go-wrapper download
# RUN go-wrapper install

# EXPOSE 8080